name: Update Contributions

on:
  schedule:
    # Run monthly on the 1st at midnight UTC
    - cron: '0 0 1 * *'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/update-contributions.yml'
      - '.github/scripts/update-contributions.py'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: none
  issues: none
  statuses: none

jobs:
  update-contributions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c
        with:
          python-version: '3.11'

      - name: Run contributions update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/update-contributions.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Check if there are changes to commit
          if git diff --quiet README.md; then
            echo "No changes to commit"
          else
            git add README.md
            git commit -m "chore: update open source contributions"
            git push
          fi
