name: Update Blog Roll

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/update-blog-posts.yml'
      - '.github/scripts/update-blog-posts.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-blog-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run blog post update script
        run: python .github/scripts/update-blog-posts.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Check if there are changes to commit
          if git diff --quiet README.md; then
            echo "No changes to commit"
          else
            git add README.md
            git commit -m "chore: update blog roll from RSS feed"
            git push
          fi
